"""End-to-end tests against a real ffmpeg, on clips generated by ffmpeg.

Slower than the unit tests (a few seconds each) but they are the only thing
that proves the pipeline actually produces playable, correctly-oriented files.
Skipped automatically when ffmpeg is absent.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from compvdo.batch import plan_jobs, run_batch
from compvdo.encode import CancelToken, run as encode_run
from compvdo.model import JobSpec
from compvdo.plan import output_path, target_container
from compvdo.probe import FFmpegMissing, detect_caps, info
from compvdo.verify import check


@pytest.fixture(scope="session")
def caps():
    try:
        return detect_caps()
    except FFmpegMissing:
        pytest.skip("ffmpeg not installed")


def make_clip(caps, path: Path, *, seconds=2, size="640x360", rate=30,
              audio=True, rotate=None, vcodec="libx264", bitrate="4M") -> Path:
    argv = [str(caps.ffmpeg), "-hide_banner", "-v", "error", "-y",
            "-f", "lavfi", "-i", f"testsrc2=size={size}:rate={rate}:duration={seconds}"]
    if audio:
        argv += ["-f", "lavfi", "-i", f"sine=f=440:d={seconds}", "-c:a", "aac"]
    argv += ["-c:v", vcodec, "-b:v", bitrate, str(path)]
    subprocess.run(argv, check=True, capture_output=True)
    if rotate is not None:
        # The rotate tag only sticks on a remux, not on the encode that made
        # the file — see docs/checkpoints.md.
        rotated = path.with_name("r_" + path.name)
        subprocess.run([str(caps.ffmpeg), "-hide_banner", "-v", "error", "-y",
                        "-i", str(path), "-c", "copy",
                        "-metadata:s:v:0", f"rotate={rotate}", str(rotated)],
                       check=True, capture_output=True)
        rotated.replace(path)
    return path


def compress(caps, src: Path, **kw) -> tuple:
    i = info(src, caps)
    ext = target_container(i.container, kw.get("mode", "medium"))
    spec = JobSpec(src=i, dst=output_path(src, ext), **kw)
    return spec, encode_run(spec, caps)


# --- the happy path --------------------------------------------------------

def test_compress_verify_and_shrink(caps, tmp_path):
    src = make_clip(caps, tmp_path / "clip.mp4")
    spec, outcome = compress(caps, src)
    assert outcome.ok, outcome.stderr_tail
    assert spec.dst.name == "clip_compressed.mp4"          # R1.1
    assert spec.dst.parent == src.parent
    assert spec.dst.stat().st_size < src.stat().st_size
    assert check(spec.src, spec.dst, caps)                 # R8


def test_original_is_untouched(caps, tmp_path):
    src = make_clip(caps, tmp_path / "clip.mp4")
    before = (src.stat().st_size, src.stat().st_mtime, src.read_bytes()[:4096])
    compress(caps, src)
    assert (src.stat().st_size, src.stat().st_mtime, src.read_bytes()[:4096]) == before


def test_mtime_is_carried_across(caps, tmp_path):
    src = make_clip(caps, tmp_path / "clip.mp4")
    spec, _ = compress(caps, src)
    assert abs(spec.dst.stat().st_mtime - src.stat().st_mtime) < 1.0      # R5.3


def test_no_temp_files_survive(caps, tmp_path):
    src = make_clip(caps, tmp_path / "clip.mp4")
    compress(caps, src)
    assert list(tmp_path.glob(".compvdo-tmp-*")) == []


# --- orientation, the classic phone-video bug ------------------------------

def test_portrait_clip_stays_portrait(caps, tmp_path):
    src = make_clip(caps, tmp_path / "p.mp4", size="640x360", rotate=90)
    i = info(src, caps)
    assert i.rotation in (90, 270) and i.display_width < i.display_height
    spec, outcome = compress(caps, src)
    assert outcome.ok
    out = info(spec.dst, caps)
    # ffmpeg bakes the rotation into the pixels, so the CODED size legitimately
    # swaps. What must not change is what the viewer sees.
    assert (out.display_width, out.display_height) == (i.display_width, i.display_height)
    assert check(i, spec.dst, caps)                         # R5.1


# --- audio -----------------------------------------------------------------

def test_silent_source_stays_silent(caps, tmp_path):
    src = make_clip(caps, tmp_path / "s.mp4", audio=False)
    spec, outcome = compress(caps, src)
    assert outcome.ok and info(spec.dst, caps).acodec is None


def test_audio_survives(caps, tmp_path):
    src = make_clip(caps, tmp_path / "a.mp4")
    spec, _ = compress(caps, src)
    assert info(spec.dst, caps).acodec is not None          # R6.1


# --- modes -----------------------------------------------------------------

def test_lower_quality_gives_a_smaller_file(caps, tmp_path):
    sizes = {}
    for mode in ("low", "high"):
        src = make_clip(caps, tmp_path / f"{mode}.mp4")
        spec, outcome = compress(caps, src, mode=mode)
        assert outcome.ok
        sizes[mode] = spec.dst.stat().st_size
    assert sizes["low"] < sizes["high"]                     # R3


@pytest.mark.skipif("ffv1" not in (detect_caps().encoders if True else set()),
                    reason="ffv1 not available")
def test_archive_is_bit_exact_and_usually_bigger(caps, tmp_path):
    src = make_clip(caps, tmp_path / "arc.mp4")
    spec, outcome = compress(caps, src, mode="archive")
    assert outcome.ok
    assert spec.dst.suffix == ".mkv", "FFV1 is not a legal MP4 codec"
    assert any("LARGER" in n for n in outcome.plan.notes)   # R3.2
    assert _frame_hashes(caps, src) == _frame_hashes(caps, spec.dst)


def _frame_hashes(caps, path: Path) -> str:
    """Decoded-frame hashes, ignoring timestamps.

    The PSNR filter is NOT usable for this: the two files carry different
    timebases, so it compares misaligned frames and reports ~25 dB on files
    that are provably identical.
    """
    proc = subprocess.run(
        [str(caps.ffmpeg), "-v", "error", "-i", str(path), "-map", "0:v",
         "-pix_fmt", "yuv420p", "-f", "framemd5", "-"],
        capture_output=True, text=True, check=True)
    return "".join(line.split(",")[-1].strip()
                   for line in proc.stdout.splitlines() if not line.startswith("#"))


# --- cancel ----------------------------------------------------------------

def test_cancel_stops_fast_and_leaves_nothing_behind(caps, tmp_path):
    import threading
    import time
    src = make_clip(caps, tmp_path / "long.mp4", seconds=30, size="1920x1080",
                    bitrate="12M")
    i = info(src, caps)
    spec = JobSpec(src=i, dst=output_path(src, "mp4"), mode="high")
    token = CancelToken()
    threading.Timer(1.0, token.cancel).start()

    started = time.monotonic()
    outcome = encode_run(spec, caps, cancel=token)
    elapsed = time.monotonic() - started

    assert outcome.cancelled and not outcome.ok
    assert elapsed - 1.0 < 1.0, "cancel must land within a second (R12.2)"
    assert not spec.dst.exists()
    assert list(tmp_path.glob(".compvdo-tmp-*")) == []      # R2.4
    assert src.exists()


# --- batch -----------------------------------------------------------------

def test_batch_isolates_a_bad_file(caps, tmp_path):
    good = [make_clip(caps, tmp_path / f"g{n}.mp4") for n in range(2)]
    (tmp_path / "bad.mp4").write_bytes(b"not a video")
    infos = [info(p, caps) for p in good]
    specs, _ = plan_jobs(infos)
    results = run_batch(specs, caps, resume_in=tmp_path)
    assert [r.status for r in results] == ["ok", "ok"]      # R9.3


def test_batch_skips_work_recorded_in_an_earlier_run(caps, tmp_path):
    """R9.2 — the resume path, driven from a run file rather than from timing.

    Simulating the interrupt with a timer would make this flaky, so the run
    state is seeded directly: that is exactly what a killed run leaves behind.
    """
    import json

    clips = [make_clip(caps, tmp_path / f"c{n}.mp4") for n in range(3)]
    infos = [info(p, caps) for p in clips]
    specs, _ = plan_jobs(infos)

    (tmp_path / ".compvdo-run.json").write_text(json.dumps({
        "started": 0.0, "mode": "medium",
        "done": {str(clips[0].resolve()): {"status": "ok", "dst_size": 123}},
        "failed": {},
    }))

    results = run_batch(specs, caps, resume_in=tmp_path)
    assert results[0].status == "skipped"
    assert [r.status for r in results[1:]] == ["ok", "ok"]
    assert not (tmp_path / "c0_compressed.mp4").exists(), "skipped file was re-encoded"


def test_a_run_file_for_a_different_mode_is_ignored(caps, tmp_path):
    # Resuming a 'medium' run into a 'high' run would silently leave a folder
    # with a mix of two quality settings.
    import json

    src = make_clip(caps, tmp_path / "c.mp4")
    (tmp_path / ".compvdo-run.json").write_text(json.dumps({
        "started": 0.0, "mode": "low",
        "done": {str(src.resolve()): {"status": "ok", "dst_size": 1}}, "failed": {},
    }))
    specs, _ = plan_jobs([info(src, caps)], mode="high")
    assert run_batch(specs, caps, resume_in=tmp_path)[0].status == "ok"


def test_a_completed_batch_clears_its_run_file(caps, tmp_path):
    src = make_clip(caps, tmp_path / "c.mp4")
    specs, _ = plan_jobs([info(src, caps)])
    run_batch(specs, caps, resume_in=tmp_path)
    assert not (tmp_path / ".compvdo-run.json").exists()


def test_rerun_on_a_folder_does_not_make_duplicates(caps, tmp_path):
    src = make_clip(caps, tmp_path / "clip.mp4")
    i = info(src, caps)
    specs, already = plan_jobs([i])
    run_batch(specs, caps)
    specs2, already2 = plan_jobs([i])
    assert specs2 == [] and len(already2) == 1
    assert not list(tmp_path.glob("*(2)*"))


# --- delete gating ---------------------------------------------------------

def test_delete_is_refused_when_the_output_grew(caps, tmp_path, monkeypatch):
    # archive mode on lossy input reliably grows the file, which is the exact
    # case R7.2 exists for.
    src = make_clip(caps, tmp_path / "arc.mp4")
    i = info(src, caps)
    spec = JobSpec(src=i, dst=output_path(src, "mkv"), mode="archive",
                   delete_original=True)
    results = run_batch([spec], caps)
    assert results[0].status == "grew"
    assert not results[0].deleted and src.exists()


def test_delete_moves_the_original_to_a_trash_we_can_find(caps, tmp_path, monkeypatch):
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setattr(Path, "home", staticmethod(lambda: home))
    monkeypatch.delenv("XDG_DATA_HOME", raising=False)
    monkeypatch.setattr("shutil.which", lambda _: None)     # force the manual path

    work = tmp_path / "vids"
    work.mkdir()
    src = make_clip(caps, work / "clip.mp4")
    i = info(src, caps)
    spec = JobSpec(src=i, dst=output_path(src, "mp4"), delete_original=True)
    results = run_batch([spec], caps)

    assert results[0].status == "ok" and results[0].verified and results[0].deleted
    assert not src.exists()
    assert (home / ".local/share/Trash/files/clip.mp4").exists()     # R2.3
